### ISSUE TITLE
Crashes after taking shard out

### ISSUE THREAD

**Issue by AndyGJorgensen** [Lemonszz/SimpleTeleporters#11]
With a Tinkers Construct crafting station directly next to the teleporter you can see an inventory inside of the teleporter when the crafting station is open.  Taking the shard out will cause the game to lock up for a while and eventually crash.  After relaunching the world the issue is gone and the shard that was attempted to be taken out of the teleporter is gone.

**Comment by Lemonszz** [comment]
Could you post a crash report? I have an idea of what causes it, but a crash report would be nice to verify.

**Comment by AndyGJorgensen** [comment]
[crash-2017-08-05_13.57.34-server.txt](https://github.com/Lemonszz/SimpleTeleporters/files/1202753/crash-2017-08-05_13.57.34-server.txt)
