### ISSUE TITLE
Suggestion: Multidimension

### ISSUE THREAD

**Issue by JomiliDesign** [Lemonszz/SimpleTeleporters#12]
Hi Lemon,

it would be awesome if you could provide a function to make your mod working in multidimensions. Is this possible?

Have a nice day

**Comment by acandylevey** [comment]
Would also love to see this!

**Comment by Nuinethir** [comment]
Agreed. Would love to be able to have this jump between my Compact Machines dimension and other worlds (Overworld, Nether, End, Deep Dark, etc). Thanks!

**Comment by talesofmabria** [comment]
Was this ever added?  I can't find info on the Curse Forge page or this one.

**Comment by Lemonszz** [comment]
No, and it isn't planned.
