### ISSUE TITLE
Request: Option to tweak the furnace recipe from Eye of Ender to Ender Pearl

### ISSUE THREAD

**Issue by vico93** [Lemonszz/SimpleTeleporters#15]
Self-explanatory.

For people like me who dont spend much time in Nether it would be a nice addition.

Thanks in advance!

**Comment by Lemonszz** [comment]
I'll be adding crafting config at some point.

In the mean time, you could use something like this https://minecraft.curseforge.com/projects/crafttweaker

**Comment by vico93** [comment]
Okay, thanks!
