### ISSUE TITLE
Version 1.12.2-3.0.0 - Ender Shards from pads all disappear and alignment problems

### ISSUE THREAD

**Issue by TheOrionsun** [Lemonszz/SimpleTeleporters#16]
Hello, Thank you for all your time and work on this mod.

I just tried your update 3.0.0 and all the Ender Shards disappear from the Teleporter pads when I enter a game that had 2.1.5 loaded. This may be unavoidable from updates you made so not a real issue.

Also, when I get all the Teleporters linked again, when I stand on center of pad and Shift to other Teleporter it puts me just off the corner of that pad, which may be in a wall or whatever is next to. This does not happen in 2.1.5. Are you able to correct this alignment issue?

Thanks again,

**Comment by Lemonszz** [comment]
Thanks for the report.

I uploaded a new version that, one approved, can be found here:
https://minecraft.curseforge.com/projects/simple-teleporters/files/2512466

It fixes the teleport offset issue.

Let me know if you have any more issues.
