### ISSUE TITLE
Ender shards are uncraftable

### ISSUE THREAD

**Issue by ghost** [Lemonszz/SimpleTeleporters#17]
Hey I unhappily detected a bug that makes the mod unplayable. The ender shards aren't craftable! You can't heat up an ender eye in a furnace in order to obtain a ender shard.
I hope you fix your last version for mc1.12.

**Comment by Lemonszz** [comment]
Oops!

This has been fixed 
https://minecraft.curseforge.com/projects/simple-teleporters/files/2512726

**Comment by ghost** [comment]
Cool! ;)
