### ISSUE TITLE
Suggestion: Integration with Xaeros mods (WorldMap and MiniMap)

### ISSUE THREAD

**Issue by vico93** [Lemonszz/SimpleTeleporters#18]
Is this possible in your side or it need to be done fully by Xaero?

I mean at least show the teleporter location in the minimap (and the map from xaeros world map too), or better to actually integraty the teleporters with the waypoint system.

Anyway thanks in advance for your mod!

**Comment by Lemonszz** [comment]
Good idea but unfortunately, I'm not planning any mod-integration for this Simple Teleporters.
