### ISSUE TITLE
Crash on Forge 1.13.2 - 25.0.99

### ISSUE THREAD

**Issue by Tokenyet** [Lemonszz/SimpleTeleporters#22]
I'm pretty sure It's crashed by this mod, because I just updated Forge, and check everything right, and then add this only mod.

After generating world, and minecraft crashed to lanucher stage.

It seems to be Lemon lib's problem.

**Comment by insanj** [comment]
@Tokenyet Please post the error or crash log here, otherwise we can't do much to help.
