### ISSUE TITLE
Crash on forge 1.13.2 - 25.0.107

### ISSUE THREAD

**Issue by XiirTaM** [Lemonszz/SimpleTeleporters#23]
With LemonLib and SimpleTeleporters when I launch my World, it's loading until 100% and after it save the world and crash. (See crash log)
[crash-2019-04-05_01.12.21-client.txt](https://github.com/Lemonszz/SimpleTeleporters/files/3045789/crash-2019-04-05_01.12.21-client.txt)

**Comment by Lemonszz** [comment]
Looks like an issue with Carry On
