### ISSUE TITLE
crafting broken in survival 1.11.2

### ISSUE THREAD

**Issue by darrenhollick** [Lemonszz/SimpleTeleporters#6]
In survival 1.11.2 you cannot craft the teleporter.  You are able to make ender crystals in the furnace and you can link them to a spot on the ground but then you can't follow the rest of your instructions to use this mode because you cannot craft the teleporter.  There are no errors produced at the client or server it just acts as if the crafting recipe is invalid.

**Comment by Lemonszz** [comment]
I can't recreate this, I crafted one for myself yesterday in my own playthough. 

What crafting setting do you have on in the config file.
If you're playing on a server, does the server's config match your own.

**Comment by darrenhollick** [comment]
I am unfamiliar with the config files.. I installed it on my client and on
the server simply by dropping the jar file in the mods folder.  If you tell
me what to look for I'm happy to get you anything you want.

**Comment by darrenhollick** [comment]
I think I found the file you're referring to and both the client and server match... here are the contents:

# Configuration file

block {
    # The amount of portal particles that will come out of the teleporter every display tick [range: 0 ~ 2147483647, default: 5]
    I:"Teleporter Particle Amount"=5
}


crafting {
    # The difficulty of crafting a teleporter block. 0 = Quartz, 1 = End Stone, 2 = Nether Star, 3 = Uncraftable [range: 0 ~ 3, default: 0]
    I:"Teleporter Crafting Difficulty"=0
}


teleportation {
    # After teleporting, the player will face the direction they were facing when linking the crystal [default: true]
    B:"Teleportation Use Crystal Direction"=true
}

**Comment by Lemonszz** [comment]
That's strange..

If you have a recipe viewer mod (JEI/NEI), does it show you the recipe?
Do you have Sponge installed? If so, if you remove it, can you craft them? In the past I've heard that is an issue.

**Comment by darrenhollick** [comment]
I don't have a recipe viewer mod.  Here are the only other mods installed on the client/server:

BBOutlineReloaded-Forge1.11.2-1.0.0-beta16
BuildHelper-Mod-1.11.2
FinderCompass-1.11.2
LLOverlayReloaded-1.1.3-mc1.11.2
Tree-Chopper-Mod-1.11.0

**Comment by Lemonszz** [comment]
I just released a new build, it fixed a bug related to recipes, but not specifically this one.
If you could update to the new version and try it out, that would be awesome.

Also make sure you're using quartz blocks in the recipe and not something like iron/snow by mistake!

**Comment by darrenhollick** [comment]
/me hangs his head in shame...

I just updated... however, I was using the wrong blocks... I just looked at the picture and since there wasn't a description of the recipe I made an embarrassing mistake.  Sorry for the trouble and for humoring me!

**Comment by Lemonszz** [comment]
Haha, all good, i've done similar!
