### ISSUE TITLE
Can't craft "Ender Shard"

### ISSUE THREAD

**Issue by electrosven** [Lemonszz/SimpleTeleporters#8]
I can craft "Teleporter", but the furnace does nothing with the Ender eye.
Can use Ender Shard in creative mode.
Minecraft 1.12
Forge 14.21.1.2395 (last)
OptiFine 1.12 HD U C4

**Comment by Lightone** [comment]
same problem simpleteleporters-1.12-2.1.4, but work fine with simpleteleporters-1.12-2.1.3

**Comment by Lemonszz** [comment]
Thanks for the report.

I'm away for a few days and won't be able to fix it right away, but thanks for bringing it to my attention. I'll fix it as soon as I'm back!

**Comment by Lemonszz** [comment]
This is now fixed!
